// // Mocks generated by Mockito 5.3.1 from annotations
// // in mobile_application_srisawad/test/user_management/user_profile_test.dart.
// // Do not manually edit this file.

// // ignore_for_file: no_leading_underscores_for_library_prefixes
// import 'dart:async' as _i4;

// import 'package:mobile_application_srisawad/models/user_profile_data.dart'
//     as _i2;
// import 'package:mobile_application_srisawad/modules/userProfile/index.dart'
//     as _i3;
// import 'package:mockito/mockito.dart' as _i1;

// // ignore_for_file: type=lint
// // ignore_for_file: avoid_redundant_argument_values
// // ignore_for_file: avoid_setters_without_getters
// // ignore_for_file: comment_references
// // ignore_for_file: implementation_imports
// // ignore_for_file: invalid_use_of_visible_for_testing_member
// // ignore_for_file: prefer_const_constructors
// // ignore_for_file: unnecessary_parenthesis
// // ignore_for_file: camel_case_types
// // ignore_for_file: subtype_of_sealed_class

// class _FakeUserProfileData_0 extends _i1.SmartFake
//     implements _i2.UserProfileData {
//   _FakeUserProfileData_0(
//     Object parent,
//     Invocation parentInvocation,
//   ) : super(
//           parent,
//           parentInvocation,
//         );
// }

// /// A class which mocks [UserProfile].
// ///
// /// See the documentation for Mockito's code generation for more information.
// class MockUserProfile extends _i1.Mock implements _i3.UserProfile {
//   MockUserProfile() {
//     _i1.throwOnMissingStub(this);
//   }

//   @override
//   _i4.Future<_i2.UserProfileData> getUserProfile() => (super.noSuchMethod(
//         Invocation.method(
//           #getUserProfile,
//           [],
//         ),
//         returnValue:
//             _i4.Future<_i2.UserProfileData>.value(_FakeUserProfileData_0(
//           this,
//           Invocation.method(
//             #getUserProfile,
//             [],
//           ),
//         )),
//       ) as _i4.Future<_i2.UserProfileData>);
// }
