name: arunsawadvn
description: Srisawad Mobile Application for Customer of srisawad

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is pref-erred for private packages.
# publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.65+66

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  cloud_firestore: ^4.3.1
  firebase_analytics: ^10.1.0
  firebase_messaging: ^14.2.0
  overlay_support:
  lottie: ^1.4.1
  google_maps_flutter: ^2.2.3
  firebase_auth: ^4.2.5
  http: ^0.13.5
  logger: ^1.1.0
  flutter_riverpod:
  flutter_native_splash: ^2.2.8
  equatable: ^2.0.5
  flutter_bloc: ^8.0.0
  flutter_dotenv: ^5.0.2
  google_fonts: ^3.0.1
  pattern_formatter: ^2.0.0
  flutter_markdown: ^0.6.12
  flutter_svg: ^1.1.5
  hexcolor: ^2.0.7
  modal_bottom_sheet: ^2.1.2
  flutter_local_notifications: ^11.0.1
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  url_launcher: ^6.1.6
  location: ^4.4.0
  geolocator: ^9.0.2
  http_interceptor: ^1.0.2
  image_picker: ^0.8.6
  image_gallery_saver: ^1.7.1
  firebase_storage: ^11.0.10
  expandable_text: ^2.3.0
  flutter_masked_text2: ^0.9.1
  intl: ^0.17.0
  timelines: ^0.1.0
  flash: ^2.0.5
  device_info_plus: ^8.0.0
  json_annotation: ^4.7.0
  internet_connection_checker: ^1.0.0+1
  firebase_core_platform_interface: 4.5.2
  package_info_plus: ^3.0.2
  currency_text_input_formatter: ^2.1.8
  navigation_history_observer: ^1.1.0
  flutter_pdfview: ^1.2.1
  auto_size_text: ^3.0.0
  mask_text_input_formatter: ^2.4.0
  permission_handler: ^10.2.0
  firebase_crashlytics: 3.0.10
  local_auth: ^2.1.3
  devicelocale: ^0.5.5
  android_id: ^0.1.3+1

dev_dependencies:
  # flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  json_serializable: ^6.5.4
  build_runner: ^2.3.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ios-app-icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  bloc_test: ^9.0.0
  build_runner: ^2.1.11
  mockito:
  test:

  flutter_lints: ^2.0.0

# flutter_icons:
# android: true
# ios: true
# image_path: "assets/splash-screen-logo.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# flutter_native_splash:
#   background_image: "assets/SplashBackground.png" # "assets/SplashBackground.png"
#   android: true
#   ios: true
#   fullscreen: true
#   remove_alpha_ios: true
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: NotoSansThai
      fonts:
        - asset: assets/fonts/static/NotoSansThai/NotoSansThai-Regular.ttf
        - asset: assets/fonts/static/NotoSansThai/NotoSansThai-Bold.ttf
          weight: 700
    - family: QuickSans
      fonts:
        - asset: assets/fonts/static/NotoSansThai/NotoSansThai-Regular.ttf
        - asset: assets/fonts/static/NotoSansThai/NotoSansThai-Bold.ttf
          weight: 700
    - family: NotoSansThaiSemiBold
      fonts:
        - asset: assets/fonts/static/NotoSansThai/NotoSansThai-SemiBold.ttf
    - family: NotoSansThaiMedium
      fonts:
        - asset: assets/fonts/static/NotoSansThai/NotoSansThai-Medium.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
dependency_overrides:
  intl: ^0.17.0
