// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDirjqI3As_IKFrBuJYYFiV2JGuiOschXA',
    appId: '1:999302187733:web:e1d3f63190e1422767305c',
    messagingSenderId: '999302187733',
    projectId: 'srisawad-mobile-app-qa-360402',
    authDomain: 'srisawad-mobile-app-qa-360402.firebaseapp.com',
    storageBucket: 'srisawad-mobile-app-qa-360402.appspot.com',
    measurementId: 'G-SX92S15JC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPgXT3ovD0LivVa6Zjc2BEf2lYse-JwUU',
    appId: '1:999302187733:android:d568e72be43c562c67305c',
    messagingSenderId: '999302187733',
    projectId: 'srisawad-mobile-app-qa-360402',
    storageBucket: 'srisawad-mobile-app-qa-360402.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsrtqHeV-1Q0mnT0Q8fahCHnkEvhAt2kw',
    appId: '1:999302187733:ios:f3466e83a1189b5067305c',
    messagingSenderId: '999302187733',
    projectId: 'srisawad-mobile-app-qa-360402',
    storageBucket: 'srisawad-mobile-app-qa-360402.appspot.com',
    iosClientId: '999302187733-9vtcct2ni105irsa6ffeiot60gkisicl.apps.googleusercontent.com',
    iosBundleId: 'com.interm.mobileApplicationSrisawad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsrtqHeV-1Q0mnT0Q8fahCHnkEvhAt2kw',
    appId: '1:999302187733:ios:cdb51b717232019f67305c',
    messagingSenderId: '999302187733',
    projectId: 'srisawad-mobile-app-qa-360402',
    storageBucket: 'srisawad-mobile-app-qa-360402.appspot.com',
    iosClientId: '999302187733-fafedagskhmssc84406su1dj3qt64itk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApplicationSrisawad',
  );
}